# Generated by Django 4.2.5 on 2023-10-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_type',
            field=models.CharField(default='SELF_PICKUP', max_length=20),
        ),
    ]
