# Generated by Django 4.2.5 on 2023-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.CharField(max_length=400),
        ),
    ]
